version: '3'
services:
    nginx:
        image: nginx:1.10.3
        container_name: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        networks:
            - frontend
        volumes:
            - ./nginx:/etc/nginx/conf.d  #nginx配置文件目录
            - /c/www/home:/home
    php5.6:
        build:
            context: ./php5.6
        image: oryxtc/local-php5.6
        container_name: php5.6
        restart: always
        privileged: true
        networks:
            - frontend
            - backend
        volumes:
            - ./php/php.ini:/usr/local/etc/php/php.ini  #php配置文件路径
            - /c/www/home:/home
    php7:
        build:
            context: ./php7
        image: oryxtc/local-php7
        container_name: php7
        restart: always
        privileged: true
        networks:
            - frontend
            - backend
        volumes:
            - ./php7/www.conf:/usr/local/etc/php-fpm.d/www.conf  #php-fpm配置文件路径
            - ./php7/local-php.ini:/usr/local/etc/php/conf.d/local-php.ini  #php配置文件路径
            - /c/www/home:/home
    mysql5.6:
        image: mysql:5.6
        container_name: mysql5.6
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
        networks:
            - backend
        volumes:
            - ./mysql/local.cnf:/etc/mysql/conf.d/local.cnf
            - ./secrets/mysql-root:/run/secrets/mysql-root
            - mysql_5.6_volume:/var/lib/mysql
    mongo:
        image: mongo:4
        container_name: mongo4
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: needtofile
        networks:
            - backend 
        volumes:
            - mongo_4_volume:/data/db           
    redis:
        image: redis:4.0-alpine
        container_name: redis
        restart: always
        ports:
            - 6379:6379
        networks:
            - backend
        volumes:
            - ./redis/redis.conf:/etc/redis.conf
        command: ["redis-server","/etc/redis.conf"]    
networks:
    frontend:
    backend:
volumes:
    mysql_5.6_volume:
    mongo_4_volume: