version: '3'
services:
    nginx:
        image: nginx:1.10.3
        container_name: oryxtc-nginx
        restart: always
        ports:
        - 80:80
        - 443:443
        links:
        - php:php_server
        - php7:php7_server
        volumes:
        - ./nginx:/etc/nginx/conf.d  #nginx配置文件目录
        - oryxtc-volume:/home
    php:
        build:
            context: ./php
        image: oryxtc/oryxtc-php
        container_name: oryxtc-php
        restart: always
        privileged: true
        links:
        - mysql:mysql_server
        - redis:redis_server
        volumes:
        - ./php/php.ini:/usr/local/etc/php/php.ini  #php配置文件目录
        - oryxtc-volume:/home
    php7:
        build:
            context: ./php7
        image: oryxtc/oryxtc-php7
        container_name: oryxtc-php7
        restart: always
        privileged: true
        links:
        - mysql:mysql_server
        - redis:redis_server
        volumes:
        - ./php7/php.ini:/usr/local/etc/php/php.ini  #php配置文件目录
        - oryxtc-volume:/home
    mysql:
        image: mysql:5.7
        container_name: oryxtc-mysql
        restart: always
        ports:
        - 3306:3306
        volumes:
        - ./secrets/mysql-root:/run/secrets/mysql-root
        - mysql-volume:/var/lib/mysql
        environment:
        - MYSQL_USER=oryxtc
        - MYSQL_PASSWORD=123456
        - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
    redis:
        image: redis:4.0-alpine
        container_name: oryxtc-redis
        restart: always
        ports:
        - 6379:6379
volumes:
    mysql-volume:
    oryxtc-volume:
        driver: local-persist
        driver_opts:
            mountpoint: /d/www/oryxtc